name: actionssuite

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    name: test-cases
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }  
    - name: Install dependencies
      run: npm install
    - name: Running Test
      run: npm test
